name: made by yuliya
favicon: null
layout_spectrum: 0.9687
typography_spectrum: 0.87719
title: art by yuliya skurska
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#bfbfbf'
    - '#8e8e8e'
    - '#616161'
  brandStrength: 0.1875
  lightness: 1
  saturation: 1
  rhythmicContrast: 0
purpose: []
